# Generated by Django 5.1.7 on 2025-03-18 09:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leadsapp", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="assigned_to",
        ),
        migrations.AddField(
            model_name="lead",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="assigned_leads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
