# Generated by Django 5.1.7 on 2025-03-20 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leadsapp", "0003_remove_lead_assigned_to_lead_assigned_to"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_leads", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Communication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("call", "Call"),
                            ("email", "Email"),
                            ("chat", "Chat"),
                            ("meeting", "Meeting"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="attachments/"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="communications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications",
                        to="leadsapp.lead",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["lead"], name="leadsapp_co_lead_id_961f6c_idx")
                ],
            },
        ),
    ]
