# Generated by Django 5.1.7 on 2025-04-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leadsapp", "0006_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communication",
            name="interaction_type",
            field=models.CharField(
                choices=[
                    ("call", "Call"),
                    ("email", "Email"),
                    ("chat", "Chat"),
                    ("meeting", "Meeting"),
                ],
                default="email",
                max_length=50,
            ),
        ),
    ]
